### ISSUE TITLE
Open source transfer and branch realignment

### ISSUE THREAD

**Issue by sodabrew** [sodabrew/puppet-dashboard#253]
Transfer of Puppet Dashboard home:
- [x] Move repo from @puppetlabs to @sodabrew
  - [x] Work with GitHub support to enable this, due to existence of http://github.com/sodabrew/puppet-dashboard-wip
- [x] Create `1.2-stable` branch from `master`
- [x] Merge `rails3` branch to `master`
- [x] 2.0 == `master` branch was: Open question: `2.0-stable` branch or use `master`?
- [x] Enable issues tracker in GitHub (Dashboard is not moving to Puppet Labs JIRA)
- [ ] Copy important issues from http://projects.puppetlabs.com/projects/dashboard as needed
- [ ] Prep release and upgrade notes from 1.2 -> 2.0
- [ ] Update README to explain the change of home, 1.2 support sunset, link to Puppet Enterprise for commercial support.

**Comment by jorhett** [comment]
I really think that #319 is an obvious necessary (and incomplete) part of this.

**Comment by jorhett** [comment]
Also, given your lack of time to respond to issues here, perhaps you should consider transitioning this to @voxpopuli or somewhere that people with interest can contribute?

**Comment by sodabrew** [comment]
I agree!

**Comment by ZeroPointEnergy** [comment]
I think we can close this. The mentioned issue tracker is long gone and I think by now no one is running 1.2 anymore. If there is something left to do from this ticked we should just create a new issue and add it to the milestone.
