### ISSUE TITLE
Preload node reports in PagesController

### ISSUE THREAD

**Issue by sodabrew** [sodabrew/puppet-dashboard#262]
https://github.com/blindsey/puppet-dashboard/commit/81cb5858da50785546692770df456c61d5f49134

`app/controllers/pages_controller.rb`

``` diff
   def home
      @all_nodes = Node.unhidden.by_report_date
 +    @all_nodes.proxy_options[:include] = { :last_apply_report => :metrics } # preload

      @unreported_nodes         = @all_nodes.unreported
      @unresponsive_nodes       = @all_nodes.unresponsive
```

**Comment by bwitt** [comment]
@blindsey @sodabrew sounds like this is a one-liner?  we should make this change?

**Comment by ZeroPointEnergy** [comment]
I actually tried this in out at one point to see if it may increase performance. It all looked very promising for smaller amount of nodes im my test environment, but with large amounts (tested with ~5k) the requests took actually longer than before, so I disabled it again.

**Comment by ZeroPointEnergy** [comment]
Going to close this because of what I mentioned above. Please reopen if you think we have to look more into this.
