### ISSUE TITLE
Use Dalli caching

### ISSUE THREAD

**Issue by sodabrew** [sodabrew/puppet-dashboard#263]
In blindsey/puppet-dashboard, use memcached via Dalli:

https://github.com/blindsey/puppet-dashboard/commit/7b96f04e535a4eda2335f9367aae151f00091fd5

https://github.com/blindsey/puppet-dashboard/commit/2d2a9604edb85caa54a88f925da0d2e3b2d065ec

https://github.com/blindsey/puppet-dashboard/commit/d7752b70b6b713c5f91161e059da127c9fe19309

https://github.com/blindsey/puppet-dashboard/commit/f725b69ba958300f52fc34c04966e9671cc64f2e

**Comment by ZeroPointEnergy** [comment]
Closing this, see #292 and #380
