### ISSUE TITLE
Managing Delayed Job Workers with Puppet?

### ISSUE THREAD

**Issue by MattPark** [sodabrew/puppet-dashboard#294]
http://docs.puppetlabs.com/dashboard/manual/1.2/bootstrapping.html#starting-and-managing-delayed-job-workers

The manual suggests a number of monitoring tools, but it sort of seems like this would be a good job for a puppet module, e.g. check to make sure there are enough workers running, if not start them.

There are some puppet-dashboard modules on puppetforge but none include the delayed job workers.  What am I missing here?

My setup is on RHEL with dashboard running in Apache httpd, and is my only rails app.

What would be the best route?  Create a new puppet-dashboard module?  Improve the one on forge? Or just write an init.d script that handles the worker on startup?

**Comment by bwitt** [comment]
I've created https://github.com/sodabrew/puppet-dashboard/issues/359 to address the manual's shortcomings around the init scripts (which are at `ext/debian/puppet-dashboard-workers.init` and `ext/redhat/puppet-dashboard-workers.init`)

Managing this worker service should be done in a `puppet-dashboard` puppet module; there's a few of them on the forge.

Please reopen this issue if I've misunderstood or there's something else to address here.
