### ISSUE TITLE
Reporting Unchanged When Heria Error

### ISSUE THREAD

**Issue by Robert-RBI** [sodabrew/puppet-dashboard#304]
When puppet is running as a windows service and an error occurs like the following

<table class="inspector">
<thead>
<tr>
<th scope="col">Level</th>
<th scope="col">Message</th>
<th scope="col">Source</th>
<th scope="col">File</th>
<th scope="col">Line</th>
<th scope="col">Time</th>
</tr>
</thead>
<tbody>
<tr class="puppet_log puppet_log_level_err">
<td class="level">
<code>err</code>
</td>
<td>
<code>Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find data item packageshare::username in any Hiera data file and no default supplied at /usr/share/puppet/modules/packages/manifests/share.pp:3 </code>
</td>
<td>
<code>Puppet</code>
</td>
<td>
<code></code>
</td>
<td>
<code></code>
</td>
<td class="nowrap">
<code>2014-10-09 10:20 UTC</code>
</td>
</tr>
<tr class="puppet_log puppet_log_level_notice">
<td class="level">
<code>notice</code>
</td>
<td>
<code>Using cached catalog</code>
</td>
<td>
<code>Puppet</code>
</td>
<td>
<code></code>
</td>
<td>
<code></code>
</td>
<td class="nowrap">
<code>2014-10-09 10:20 UTC</code>
</td>
</tr>
<tr class="puppet_log puppet_log_level_notice">
<td class="level">
<code>notice</code>
</td>
<td>
<code>Finished catalog run in 0.03 seconds</code>
</td>
<td>
<code>Puppet</code>
</td>
<td>
<code></code>
</td>
<td>
<code></code>
</td>
<td class="nowrap">
<code>2014-10-09 10:20 UTC</code>
</td>
</tr>

</tbody>
</table>

The Dashboard shows <B>unchanged</b> with a <b>green tick</b> .

If I run <b>puppet agent -t</b> and the error occurs then I get a <b>red x</b>.

Tried on puppet 3.7.2 and 3.6.1.

Puppet agents are running on a windows box

**Comment by maddop** [comment]
We are seeing the same issue. Did you identify what went wrong here?

**Comment by bwitt** [comment]
@Robert-RBI @maddop lots of changes have landed recently; is this issue still valid?

**Comment by ZeroPointEnergy** [comment]
I did a PR related to this some years ago https://github.com/sodabrew/puppet-dashboard/pull/285 which checks if the report has any logs with log level err. Since this seems to be the case here I think this is already fixed.

Unfortunately the pastebins are gone so I can't verify.

**Comment by bwitt** [comment]
ok I'm going to close this as it sounds like it should be fixed; please re-open if you're still experiencing this.
