### ISSUE TITLE
Dashboard takes too long to remove a node

### ISSUE THREAD

**Issue by reModding** [sodabrew/puppet-dashboard#309]
Hi,

I would like to reanimate a bug ticket (ok, there are exactly two tickets, but they describe the same problem) which was opened nearly two years ago at projects.puppetlabs.com:
- https://projects.puppetlabs.com/issues/6828
- https://projects.puppetlabs.com/issues/11026

The main problem is still present, because node deletion triggers `ResourceStatus.destroy` for every manifest and report that is stored in the database. If you have lots of these it takes a long time to process thousands of "DELETE" queries.
Even my well equipped MySQL server needs about one hour to delete one (!) node with all its dependecies (`rake node:del name=myagent RAILS_ENV=production`).

**Comment by ruckc** [comment]
What would you have Dashboard do though?  Do you want to leave the 
reports/resource_statuses in the database without them being accessible?

**Comment by sodabrew** [comment]
This is already resolved in this repository. You should replace Dashboard 1.2 with Dashboard 2.0 here.

**Comment by reModding** [comment]
Thank you! :+1:
