### ISSUE TITLE
puppet-dashboard user not created by the package

### ISSUE THREAD

**Issue by anarcat** [sodabrew/puppet-dashboard#313]
this document:

https://docs.puppetlabs.com/dashboard/manual/1.2/bootstrapping.html#installing-from-packages

says:

```
If you haven’t installed Dashboard from a package, you must create a user and group for Dashboard and chown all its files to be owned by that user and group:
```

i have installed puppet-dashboard from a package, and it didn't create such a user.

**Comment by anarcat** [comment]
one would need to do something like this:

```
Create missing user::
  
  addgroup --system puppet-dashboard
  adduser --system puppet-dashboard --no-create-home --home /usr/share/puppet-dashboard/
  chown -R root:puppet-dashboard /etc/puppet-dashboard/
```

but then permissions on a bunch more stuff would need to be fixed, like `/usr/share/puppet-dashboard/public/javascripts`. It always struck me as an odd security mechanism to allow apps to modify their own files, however...

**Comment by bwitt** [comment]
hi @anarcat was that an rpm or deb package you used that didn't create the user?

**Comment by anarcat** [comment]
On 2018-08-21 23:40:12, Brian Witt wrote:
> hi @anarcat was that an rpm or deb package you used that didn't create the user?

most likely .deb.

**Comment by bwitt** [comment]
ok I see the rpm file (`ext/redhat/puppet-dashboard.spec.erb`) does create a `puppet-dashboard` user and changes ownership of a bunch of stuff to that user.  

however, the debian package postinst file `ext/debian/postinst` doesn't create a user but instead `chown`s a bunch of stuff to `www-data`.  did everything work properly like that?  maybe we just need to update the docs.

**Comment by ZeroPointEnergy** [comment]
I'm closing this as it is unclear what the original issue was. Please reopen if you think this is still an issue and provide some additional information. Thanks
