### ISSUE TITLE
Report fails sanitization if optional fields in event don't exist

### ISSUE THREAD

**Issue by ssgelm** [sodabrew/puppet-dashboard#315]
I've stumbled upon a bug in puppet-dashboard's report sanitization.  At https://github.com/sodabrew/puppet-dashboard/blob/master/lib/puppet/report_sanitizer.rb#L110 it verifies all the attributes it believes is required for an event but in the puppet report reference it says "This value will be missing if the provider errored out before it could be determined." for the following attributes:
- property
- previous_value
- desired_value
- historical_value

I am working on a PR to fix this however I wanted to log an issue first.

**Comment by sodabrew** [comment]
Thanks for identifying and reporting this! I am looking forward to the PR!

**Comment by ssgelm** [comment]
For what it's worth I believe these values are only optional as of report format 4.  I will add that to the report_sanitizer and add some tests around it.

**Comment by ssgelm** [comment]
FYI, PR #316 has been submitted to fix this.

**Comment by bwitt** [comment]
fixed via https://github.com/sodabrew/puppet-dashboard/pull/354
