### ISSUE TITLE
ValueWrapper in ResourceEvent doesn't work in ruby 1.9

### ISSUE THREAD

**Issue by ssgelm** [sodabrew/puppet-dashboard#317]
As implemented in 630cd8f2973e80993a6d1cac5b2c86037a4ba805, ValueWrapper does not work correctly in ruby 1.9.  For whatever reason, in ruby 1.9 psych raises a SyntaxError which is a subclass of Exception. StandardError (which is what rescue defaults to) is also a subclass of Exception so SyntaxError is not rescued.  PR to fix including tests is coming, just wanted to give a heads up.

**Comment by bwitt** [comment]
fixed via https://github.com/sodabrew/puppet-dashboard/pull/318
