### ISSUE TITLE
Fails to parse reports submitted by puppet 4.0

### ISSUE THREAD

**Issue by skx** [sodabrew/puppet-dashboard#320]
I've configured a release of 2.0 but I see an error when processing new report submissions in the background workers.

I see this, which suggests to me that the report-format has changed, or otherwise the wrong thing is being saved:

```
Importing report report-7221-5.yaml at 2015-04-22 19:26 UTC
tags was supposed to be a Array, but was a Puppet::Util::TagSet
```

**Comment by sodabrew** [comment]
I haven't begun testing with Puppet 4 - so any help on this front is appreciated. I suspect the best way to begin ingesting Puppet 4.0 reports will be as JSON rather than YAML.

**Comment by skx** [comment]
I suspect this "bug report" is really a feature request, which should be retagged and/or closed.

But yes I suspect the JSON output would be more useful.  I wrote some simple code to try reading the bodies of the submissions and the YAML does make reference to lots of toy objects which are designed to hold sets/hashes of data.

If you go down the route of creating a compatibility-layer of objects to deparse things will get murkier and murkier over time.

For the moment I guess the key thing is to recognize the type of the incoming submission and cleanly ignore things that aren't recognized.  At the moment I've just done a sleazy match on the 4.0 reports as the body contains:

      ...
      transaction_uuid: dcd4f2dd-781b-4b45-97e9-019139ce413e
      puppet_version: 4.0.0
      report_format: 4
      ...

Matching that _prior_ to parsing the YAML allowed me to discard the submissions and avoid errors.   Not ideal, and not what I want, but enough for the moment.

**Comment by arnaudmm** [comment]
any hint how to quick fix that ? I'm trying to debug it but any help would be appreciated

**Comment by skx** [comment]
It is not going to be a quick fix, I expect.  The format/structure has changed significantly.

**Comment by arnaudmm** [comment]
This is a pain to debug, but I got a working setup

**Comment by arnaudmm** [comment]
Ok, so here is my report:

From my point of view, the structure has changed but only for the tags value in the hash that was used to be an Array and now we have:

            "tags"=>{
                "hash"=>{
                    "info"=>true
                }
            },

A quick fix is to reset the tag key:

diff --git a/app/models/report.rb b/app/models/report.rb
index 0764d93..fb4e49f 100644
--- a/app/models/report.rb
+++ b/app/models/report.rb
@@ -83,12 +83,14 @@ class Report < ActiveRecord::Base
     attribute_hash["logs_attributes"].each do |resource_logs_hash|
       log_message = resource_logs_hash["message"].to_s
       resource_logs_hash["message"] = log_message.slice(0, 65535) if log_message.length > 65535
+      resource_logs_hash["tags"] = []
     end
     
     attribute_hash["resource_statuses_attributes"] = attribute_hash.delete("resource_statuses")
     attribute_hash["metrics_attributes"] = attribute_hash.delete("metrics")
     attribute_hash["resource_statuses_attributes"].each do |resource_status_hash|
       resource_status_hash["events_attributes"] = resource_status_hash.delete("events") || {}
+      resource_status_hash["tags"] = []
     end
     attribute_hash["metrics_attributes"] = attribute_hash["metrics_attributes"].map do |category,metric_hash|
       metric_hash.map do |name,value|
@@ -114,15 +116,26 @@ class Report < ActiveRecord::Base

**Comment by sodabrew** [comment]
Please do open a PR! It will run automatic unit tests and make it easier to merge the changes.

**Comment by arnaudmm** [comment]
Unfortunatly I don't think it is an acceptable solution.

It's ok with my workflow because I don't give a damn about tags. But my report may help someone to PR a better solution with good @skx recommandations.

**Comment by sodabrew** [comment]
Oh, does this end up dropping all tags from the report?

**Comment by arnaudmm** [comment]
yup quick and dirty, sorry but I need this dashboard for my puppet4 setup ;)

**Comment by jorhett** [comment]
@skx are you willing to share your test code as a starting point? I'll have time to focus on this next week.

**Comment by skx** [comment]
Sadly I no longer have it to hand - I remember I updated:

      def self.create_from_yaml(report_yaml)

But beyond looking for the `report_format` key I'm hazy on what I did.  I tried making progress, but didn't get very far.  Sorry to be so unhelpful - I guess, like I suggested earlier, this issue really did just turn into a feature-request rather than a useful bug-report.

**Comment by bwitt** [comment]
sorry for closing https://github.com/sodabrew/puppet-dashboard/pull/329!  I've recreated in https://github.com/sodabrew/puppet-dashboard/pull/352

**Comment by bwitt** [comment]
oh actually looks like @ZeroPointEnergy might have all the fixes needed already done

**Comment by bwitt** [comment]
fixed by https://github.com/sodabrew/puppet-dashboard/pull/354 ; please re-open if this is not the case!
