### ISSUE TITLE
externel_node

### ISSUE THREAD

**Issue by cdenneen** [sodabrew/puppet-dashboard#327]
Returning 500 error:

NameError (undefined local variable or method `environment' for #<Node:0x0000000648af20>):
  app/models/node.rb:116:in`block in configuration'
  app/models/node.rb:115:in `tap'
  app/models/node.rb:115:in`configuration'
  app/models/node.rb:130:in `to_yaml'
  lib/add_renderers.rb:10:in`block in <top (required)>'
  app/controllers/nodes_controller.rb:78:in `show'

**Comment by sodabrew** [comment]
There's a migration on the master branch; actually I probably want to split that off to a 2.1 future branch.

**Comment by cdenneen** [comment]
Is there something I need to run for this to work?

**Comment by cdenneen** [comment]
Are you planning to support puppet environments in the UI as a drop down?

**Comment by sodabrew** [comment]
In fact that's exactly what @jbussdieker and I were talking about recently. The free-text environments field may not the best choice for the long run.

**Comment by cdenneen** [comment]
@sodabrew I think this is a great feature but until I have a way to make it stop causing 500 error can we revert '0b7a40c0b3f90dbe071856977a3dffcc0239b8eb' and put in 2.1 branch as you recommended? Or are there some instructions @jbussdieker can provide?

**Comment by sodabrew** [comment]
Using revision 0b7a40c0b3f90dbe071856977a3dffcc0239b8eb is a sure bet.

**Comment by bwitt** [comment]
@cdenneen is this issue still valid? lots of changes have landed recently.

**Comment by ZeroPointEnergy** [comment]
This should be resolved in current master. Please reopen if this is not the case.
