### ISSUE TITLE
parameters.value

### ISSUE THREAD

**Issue by cdenneen** [sodabrew/puppet-dashboard#328]
when saving something like:

Key: location
Value: dmz

Database saves value as:

"--- dmz
...
"

It's almost like it's trying to write yaml?

**Comment by sodabrew** [comment]
Yes, that's correct. The schema allows this to be a complex data structure, it just doesn't have a UI for it.

**Comment by bwitt** [comment]
@cdenneen haven't heard from you in a while so I'm going to close this; if you still have questions or need to update this, please re-open.  Thanks!
