### ISSUE TITLE
Dashboard Manual link in the README loops to self

### ISSUE THREAD

**Issue by jorhett** [sodabrew/puppet-dashboard#330]
The "Full Dashboard Manual" link the README links to http://docs.puppetlabs.com/dashboard/manual which sends a redirect to this github project...

Seems the manual needs to be located somewhere else.

**Comment by darkpixel** [comment]
Makes it difficult to find out what's involved for the step "Make puppet dashboard aware"... ;)

**Comment by DIntertech** [comment]
Are there any good instructions or references on how to install?

**Comment by sodabrew** [comment]
The README has setup instructions. Are there points of unclarity?

**Comment by DIntertech** [comment]
Questions I have are things like:

What folder should the repo go into(Im on Centos 7)?
How do I configure the ports?
Does it integrate with APache or Nginx?
Do any make files have to built using make?

I am a first time puppet user. The current README seems to assume that I have a certain level of knowledge about Puppet. How can this be made easier for users like myself?

**Comment by antgel** [comment]
Hi, I'm in the same boat. I just asked about this on IRC and they said ask here. I also don't understand 1) where the manual is, and 2) How to go about bullet points "Set up Puppet to be Dashboard-aware." and
"Start the delayed job worker processes."

Any clues?

**Comment by jorhett** [comment]
So for those who would like a walk-through of the process to build up and use each feature of Dashboard, it is covered at length in Part IV of Learning Puppet 4 
  http://shop.oreilly.com/product/0636920034131.do

**Comment by jorhett** [comment]
The workaround until @sodabrew merges this is to check out the docs to your own webserver

```
cd /some/docroot/you/have
git clone https://github.com/pdxmph/puppet-dashboard/commit/f61ea66e3026346fe99e3fc739036336798efb53
```

**Comment by gyles19** [comment]
That link to the manual at git clone https://github.com/pdxmph/puppet-dashboard/commit/f61ea66e3026346fe99e3fc739036336798efb53 doc is also a 404.

**Comment by mercury00** [comment]
I'm curious what to expect from this project prior to actually installing it on a server. I was hoping that would be clarified a bit by reading the documentation. "For full documentation, see the Puppet Dashboard Manual."

I can't seem to find any such manual anywhere. I'm not asking for someone to hold my hand, I'm just trying to find basic documentation. Can this be added to the project somehow, or hosted somewhere we can find?

**Comment by gyles19** [comment]
I had the same problem. As far as I can tell, that project used to be
officially part of Puppet, but now that Puppet Enterprise exists, they've
jettisoned Dashboard and it's now only an external, unsupported project.  I
downloaded the source and studied the documentation there instead.  Never
did get it successfully installed, though.

On Wed, Mar 23, 2016 at 7:15 PM, Aaron <notifications@github.com> wrote:

> I'm curious what to expect from this project prior to actually installing
> it on a server. I was hoping that would be clarified a bit by reading the
> documentation. "For full documentation, see the Puppet Dashboard Manual."
>
> I can't seem to find any such manual anywhere. I'm not asking for someone
> to hold my hand, I'm just trying to find basic documentation. Can this be
> added to the project somehow, or hosted somewhere we can find?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sodabrew/puppet-dashboard/issues/330#issuecomment-200592422>
>



-- 

No matter what we think of Linux versus FreeBSD, etc., the one thing I
really like about Linux is that it has Microsoft worried. Anything
that kicks a monopoly in the pants has got to be good for something.
- Chris Johnson

**Comment by jorhett** [comment]
@mercury00 and @gyles19 you can download the manual from the PR linked above. Alternatively you can read the chapter on the Puppet Dashboard in Learning Puppet 4

http://my.safaribooksonline.com/book/operating-systems-and-server-administration/9781491907993/31dot-managing-network-infrastructure-with-puppet/managing_network_infrastructure_with_puppet_html#X2ludGVybmFsX0h0bWxWaWV3P3htbGlkPTk3ODE0OTE5MDc5OTMlMkZ1c2luZ19wdXBwZXRfZGFzaGJvYXJkX2h0bWwmcXVlcnk9

**Comment by mercury00** [comment]
^ I can't read that because it's a commercial product. Puppet Dashboard and github are not.

What PR are you referring to? I assume PR means pull request, but if I look at pull requests I see 13 different ones, and it's not clear what you're referring to. Can you please be more specific?

**Comment by jorhett** [comment]
@mercury00 not saying you should have to, was saying that it's currently the best documentation I'm aware of for implementing it (was my aim in writing it, due to lack of what's available now) and it's an option for you.

As for the PR, there's only one PR linked to this issue. Scroll up. (original message: "the PR linked above")

**Comment by mercury00** [comment]
Right, apologies, but "scroll up" gives me a lot more results than just pull request #319, but saying "Pull request #319" is a bit more specific.

**Comment by jorhett** [comment]
Please screencap where any other PR is mentioned on this issue.

My statement was not vague.

**Comment by gyles19** [comment]
Jorhett, I think folks are confused because some of them are seeing this thread from the mailing list, not the github.com web page, and email series has already truncated the post you're referring to.  People aren't trying to be stupid, they simply can't see what you're referring to.

For the rest of us, I believe the earlier post of Jorhett's contains this:

`cd /some/docroot/you/have
git clone https://github.com/pdxmph/puppet-dashboard/commit/f61ea66e3026346fe99e3fc739036336798efb53 doc`

Which is what I did to obtain the documentation for myself several months ago.  Sadly, my knowledge of puppet is insufficient to allow me to follow those instructions successfully, as they assume too much.  (And there is nothing wrong with that, either.)

The Puppet 4 book does have a nice chapter  on installing Dashboard, but also assumes one is using a fresh install of Puppet 4, which mine is not, so even this wasn't sufficient to overcome my knowledge deficits for installing Dashboard.

**Comment by jorhett** [comment]
> The Puppet 4 book does have a nice chapter on installing Dashboard, but also assumes one is using a fresh install of Puppet 4, which mine is not, so even this wasn't sufficient to overcome my knowledge deficits for installing Dashboard.

Happy to help, and would love to improve it. Ping me on irc/slack/twitter as jorhett

**Comment by mercury00** [comment]
johett, you don't know what client, aggregator, spider, or other service is being used to read this. "Scroll up" is /very/ vague. This, for instance, is one thing that one sees when scrolling up: 
![screenshot](https://cloud.githubusercontent.com/assets/924422/15194092/e6b8d85e-1775-11e6-92bd-19a838979235.png)
There's a lot of links there. The problem isn't that you mentioned lots of PRs on this issue, the problem is there's no comment you've made which says which PR you're referring to, and there's 13 PRs listed when I "scroll up". Specificity is actually a good thing. My simple request to clarify which one doesn't need more vague answers, it just needed "PR #319". I get that you're too cool for all of this, but I was just looking for clarification and confirmation.

**Comment by jorhett** [comment]
I'm sorry but we are totally wasting time here. You've now doubled the length of this issue arguing that you are unable to read the issue history or something. The issue is self-standing and it contains only a single PR. Use it.

**Comment by gyles19** [comment]
And with that snotty response, I've decided to not waste any more time
trying to work with puppet dashboard.  Foreman looks much easier to deal
with, so I'll be installing that, instead.

Ta ta.


On Wed, May 11, 2016 at 3:01 PM, Jo Rhett <notifications@github.com> wrote:

> I'm sorry but we are totally wasting time here. You've now doubled the
> length of this issue arguing that you are unable to read the issue history
> or something. The issue is self-standing and it contains only a single PR.
> Use it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sodabrew/puppet-dashboard/issues/330#issuecomment-218572869>
>



-- 

No matter what we think of Linux versus FreeBSD, etc., the one thing I
really like about Linux is that it has Microsoft worried. Anything
that kicks a monopoly in the pants has got to be good for something.
- Chris Johnson

**Comment by mercury00** [comment]
Yes, you've successfully doubled the length of the issue by not simply and directly answering which PR you were referring to; so far, the only PR I see here is the one I mentioned, which you've never confirmed. Thanks for the help and the attitude. Apologies for hoping this code could be used by someone other than the author. I'm sure you'll celebrate my leaving, but I wonder what the purpose of collaboration is when the people are hostile?<https://github.com/sodabrew/puppet-dashboard/issues/330#issuecomment-218577655>

**Comment by allmusic76** [comment]
It would be awesome if that link could be fixed.
The links in this thread to the Puppet 4 manual are stale, and unfortunately there are folks out there trying to use this w/ Puppet 3.8, so the link is irrelevant to begin with.

**Comment by bwitt** [comment]
Solved in https://github.com/sodabrew/puppet-dashboard/pull/319
