### ISSUE TITLE
Some Problems when  run the " bundle exec rake *** "  THANK YOU FOR Your Help!

### ISSUE THREAD

**Issue by freysong** [sodabrew/puppet-dashboard#339]
THANK YOU FOR Your Help!

MY SYSTEM VERSION INFORMATION:
1. ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
2. puppet 3.6.2
3. Rails 3.2.22.2
4. dashboard 2.0.0-beta1

I Have some Problems when I run the "bundle exec rake **\* ".

example:
[root@puppetmasternew lib]# bundle exec rake secret --trace  
(in /usr/nettv/puppet-dashboard)
rake aborted!
Resource is not a module
/usr/nettv/puppet-dashboard/lib/data_generator.rb:4
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in 
......

Then I find "/usr/nettv/puppet-dashboard/lib/data_generator.rb:4" is
"module Puppet::Resource; end"

SO I delete the line 4, it will be OK .

BUT, the report status will has some problem.The report status is always "X pending tasks".

the database (table:delayed_jobs) is recording these information:
"Job failed to load: undefined method `with_scope' for nil:NilClass. Handler: ....."

I DO NOT KNOW HOW TO FIX IT. 
BEG Your Help!

**Comment by thechase22** [comment]
did you try this?

 echo "secret_token: '$(bundle exec rake secret RAILS_ENV=production)'" >> settings.yml

**Comment by bwitt** [comment]
@freysong haven't heard back from you in a while so I'm going to close this; if you still are having an issue please reopen.  thanks!
