### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by Skunnyk** [sodabrew/puppet-dashboard#341]
Hi,

What is the state of this project ? :) 
I know everybody contribute on his free time, and I really appreciate your works.
I (still) use it in production as an ENC, and I think I'm not alone in view of all opened issues/pull requests.
There is some "active" forks ( https://github.com/swoopla/puppet-dashboard ) or usefull PR which need to be merged ( #336,  #334 or #333 for debian packaging! etc).
@sodabrew , is it a lake of time, interested, did you abandon the project ?
Do you need help or it is better to fork it to revive it ?

Another interesting project is puppetboard, but there is no ENC support (never ? https://github.com/voxpupuli/puppetboard/issues/134 ), and it also need a new maintainer ( https://github.com/voxpupuli/puppetboard/issues/305 ).

Sooo… maybe I 'm the last ENC user ? ;)

Thank you,

**Comment by larsnaesbye** [comment]
I second @Skunnyk  - we use Puppet Dashboard (1.2.23) in my business, but would like to know if there is anyone actively working on it. Also, could we perhaps identify a fixed set of things to fix before a 2.0 release?

**Comment by sodabrew** [comment]
Migrate now to the git repo as is, has been stable for a long time.

**Comment by larsnaesbye** [comment]
Will do. But if this is going to be the state for a long time, should we not make the repo version a 2.0 release?

**Comment by sodabrew** [comment]
Yes, I should, but haven't made the necessary time available to do so :(

**Comment by larsnaesbye** [comment]
If we can break it down into subtasks, maybe the rest of us can? :)

**Comment by sodabrew** [comment]
I appreciate it. There are open tickets for the items.

**Comment by larsnaesbye** [comment]
Sounds good. But maybe we can do what @Skunnyk hinted at: merge #336, #334 and #333 and then take it from there?

**Comment by skx** [comment]
FWIW I put together [a simple golang based alternative here](https://github.com/skx/puppet-summary).

* It doesn't do classes / groups, and thus can't be used as an ENC.
* It __only__ does the visualization.

Being self-contained it is less fragile and simpler to install.  It was also a fun learning experience.  In the absence of activity here it might be useful to some.

**Comment by ZeroPointEnergy** [comment]
@sodabrew I'm using the Puppet Dashboard still heavily as it is in my opinion still one of the most accurate and presents the information I need in a very clear way. However there are some parts where I would like to extend on it.

It seems to me that the time you have to maintain this project is very limited, which is just natural and happens to a lot of projects around Puppet all the time.

Since I don't just want to make another fork which gets abandoned in a few months, would you be willing to transfer the project to Voxpupuli if possible so people interested (like me at the moment) can take over maintainership easily at a central location and continue the great project?

**Comment by ZeroPointEnergy** [comment]
@bastelfreak I talked about this on the IRC channel a while ago and you told me you would have to think about it. Did you come to any conclusion if voxpupuli would be interested in hosting the repository of @sodabrew is willing to transfer the project?

There are a few PR ready to be merged which will put the project into a completely usable state with everything from newest Rails to all stable rubies and the newest Puppet 5 stuff.

**Comment by bwitt** [comment]
So I'm going to close this issue; the state is revived (at least for the short term); please send your issues and PRs!   we're in the process of figuring out longer-term plan.
