### ISSUE TITLE
report format 7 appears to fail

### ISSUE THREAD

**Issue by wyardley** [sodabrew/puppet-dashboard#345]
With Puppet 5 (I believe it's sending report_format 7; https://docs.puppet.com/puppet/5.1/format_report.html), I get a slew of these errors, and no reports are processed:

```
Importing report at 2017-08-29 23:16 UTC
    required attribute not present: kind
    Backtrace
    lib/puppet/report_sanitizer.rb:37:in `block in verify_attributes'
    lib/puppet/report_sanitizer.rb:36:in `each'
    lib/puppet/report_sanitizer.rb:36:in `verify_attributes'
    lib/puppet/report_sanitizer.rb:188:in `sanitize'
    lib/puppet/report_sanitizer.rb:10:in `sanitize'
    app/models/report.rb:122:in `create_from_yaml'
```
Has anyone gotten puppet-dashboard working with 5.x or does anyone plan on making a PR to support this? Given the status of the project, we may look at what other tools are out there also.

**Comment by skx** [comment]
I wrote my own tool as this project seems to be semi-orphaned.

I currently handle `report-format` of 5 & 6, but if you're willing to share an example I'd be happy to add support for 7 too:

* [Project](https://github.com/skx/puppet-summary)
* [Demo](https://master.steve.org.uk/)

**Comment by wyardley** [comment]
@skx Thanks -- for now, we've migrated to Puppetboard, so I'll just close this one.

**Comment by larsen0815** [comment]
See https://github.com/sodabrew/puppet-dashboard/pull/347 for a fix for this.

**Comment by anordby** [comment]
Did you actually test that patch @larsen0815 ? ;) I applied it and I still get the exact same error message, required attribute not present: kind with backtrace:

lib/puppet/report_sanitizer.rb:37:in `block in verify_attributes'
--
lib/puppet/report_sanitizer.rb:36:in `each'
lib/puppet/report_sanitizer.rb:36:in `verify_attributes'
lib/puppet/report_sanitizer.rb:188:in `sanitize'
lib/puppet/report_sanitizer.rb:10:in `sanitize'
app/models/report.rb:122:in `create_from_yaml'

**Comment by ZeroPointEnergy** [comment]
@anordby here is a fork which supports all the new formats and all the new rubies because I updated it to Rails 5.2. https://github.com/ZeroPointEnergy/puppet-dashboard

I think this project is dead and I'm just migrating my last customer away from the board so my branch will not be updated in the future as well. But at least it is like 5 years more recent than what you get here.

**Comment by anordby** [comment]
@ZeroPointEnergy Hey, thanks. Yes I am also migrating away, just wanted to have the dashboard working with old and new while migrating. It seems puppetboard is the way to go, for Puppet.

**Comment by anordby** [comment]
@ZeroPointEnergy Your changes in lib/puppet/report_sanitizer.rb in particular helped me get this somewhat working, thanks. This is what is missing in sodabrew puppet-dashboard. It's nice to have the dashboard working still while migrating to Puppet/PuppetDB 5.x..

**Comment by larsen0815** [comment]
@anordby I developed that patch for my puppet installation, so obviously yes, I tested it and it worked for me ;-)
