### ISSUE TITLE
Ruby version 2.0 is EOL

### ISSUE THREAD

**Issue by hostingnuggets** [sodabrew/puppet-dashboard#346]
The README mentions Ruby 2.0 as dependency but Ruby 2.0 is in the mean time EOL and unsupported. Does the puppet-dashboard also work with more modern versions of Ruby, for example 2.3 or 2.4?

My goal would be to run puppet-dashboard on a Debian 9 server with Puppet 4 and Ruby 2.3 or 2.4.

**Comment by bwitt** [comment]
I actually attempted to do this at one point; I think there's a change in the yaml libraries from 2.0 -> 2.4 that puppet-dashboard doesn't support?

**Comment by sodabrew** [comment]
Ruby 2.1-2.3 should be no problem. There are more changes in Ruby 2.4 that may warrant further tests before calling it clear.

**Comment by sodabrew** [comment]
Resolved by #349
