### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by ZeroPointEnergy** [sodabrew/puppet-dashboard#350]
Let's use this issue for the discussion of the continuation of the project. I removed the previous content to not confuse people who visit the project. @bwitt  and I have now collaborator access and @bwitt has already started to integrate the pending changes and work towards a new release.

**Comment by sodabrew** [comment]
There's been some suggestion to get this over to https://github.com/voxpupuli

That sounds sane to me, as does adding contributors to this repo if you'd be available to help maintain the codebase here?

I don't have a Puppet service in production at this time, so I'm not able to validate changes personally. What this really means is time to pass the torch. The work you've done on the Rails 5.2 update PR is fantastic, and I'd like to land that PR.

**Comment by bwitt** [comment]
let's get some needed PRs merged and do a release, and then get this moved over to  https://github.com/voxpupuli

**Comment by bwitt** [comment]
@ZeroPointEnergy would you be willing to make a PR to get the needed bits merged into this project?

**Comment by ZeroPointEnergy** [comment]
@bwitt @sodabrew all the relevant PR are already merged in my fork at https://github.com/ZeroPointEnergy/puppet-dashboard with additional fixes for the newest report formats. I would recommend to simply use the master from there instead of doing the whole integration work again.

Will look into the whole thing shortly.Is voxpupuli actually interested? Last time I conversed with them they where not really thrilled about it.

**Comment by ZeroPointEnergy** [comment]
Ok, I simply rebased my branch and created a new PR https://github.com/sodabrew/puppet-dashboard/pull/354

**Comment by bwitt** [comment]
ok got #354 merged.  what else do we need to do to do a release?  #253 has a partially completed list of stuff to do ; of those these are probably most important:
> Prep release and upgrade notes from 1.2 -> ~2.0~3.0
> Update README to explain the change of home, 1.2 support sunset, link to Puppet Enterprise for commercial support.

Also I notice there's still a few references to Puppetlabs that should probably be changed at some point; maybe not entirely necessary for the 3.0 release?

**Comment by ZeroPointEnergy** [comment]
I tried to group the issues into milestones so we have a clear path forward from here. The issues left in the 3.0 milestone are all documentation related because I think we should at least provide some up to date documentation about how to install the software before releasing. From the code side of things I think we are ready if no additional bugs pop up.

**Comment by ZeroPointEnergy** [comment]
@bwitt @sodabrew what do you think, whould we finally do a release? The software is updated to the most recent framework and gems, the old documentation while outdated is at least integrated and can be found.

I think it would be a good point to put out a 3.0 and signal that this project is at least somewhat maintained.

As for the way forward, I think we need to have some discussions about where we want the project to go (even if maintenance mode is the answer). I will open a separate ticket for that discussion.

**Comment by ZeroPointEnergy** [comment]
Release is on its way. Closing this
