### ISSUE TITLE
Update puppetlabs references

### ISSUE THREAD

**Issue by bwitt** [sodabrew/puppet-dashboard#358]
References in the codebase to
```
puppetlabs.com
https://github.com/puppetlabs/puppet-dashboard
redmine
```

should probably be updated as appropriate; either to a current working link at puppet or a link to elsewhere in this repo.

**Comment by sodabrew** [comment]
That footer should just go away. There's no reason to declare a copyright date on the rendered page.

**Comment by ZeroPointEnergy** [comment]
Done
