### ISSUE TITLE
Add badges to README 

### ISSUE THREAD

**Issue by bwitt** [sodabrew/puppet-dashboard#363]
Add badges to README for things like:

build status  (https://api.travis-ci.org/sodabrew/puppet-dashboard.png?branch=master)
tests passing/not passing   
test code coverage
license badge maybe?
any code quality service we're using

**Comment by ZeroPointEnergy** [comment]
Any more badged needed?

**Comment by bwitt** [comment]
Looks great thanks for all your help!
