### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by ZeroPointEnergy** [sodabrew/puppet-dashboard#368]
Ok, so I tried to update the dependencies and there are a couple of issues arising.
- pg gem is hitting a bug during compilation: https://bitbucket.org/ged/ruby-pg/issues/281/pg-gem-110-compiles-on-alpine-linux-but . There seems to be a 1.1.1 but I still had the same error. I will just pin this to the latest working version 1.0.0 for now.
- The inherited_resources gem which I have to update because the current version has a dependency constraint for "actionpack (>= 4.2, <= 5.2)" which blocks the Rails update to 5.2.1 requires now at least ruby 2.3 (why would they do that in a minor release anyway :man_shrugging:) and breaks some tests.

Since this means that we have to drop ruby 2.2 support as well the question is should we bring this update in before the 3.0 release? I have some mixed feelings delaying the release even further.

In any case, in my opinion we have to remove ruby 2.2 support right now as I really don't want to follow the bad example and do it in a minor release :wink:

WDYT?

**Comment by sodabrew** [comment]
No hard feelings: https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

**Comment by ZeroPointEnergy** [comment]
Yes, true :smile: . I recommend we wait with the Rails update until after the 3.0 release then. I create a milestone with the tickets I think are required in my opinion to release, which is mainly just documentation. Feel free to move them out or add more if you think something can be done later or is required.

**Comment by sodabrew** [comment]
I'm confused though, isn't current master already Rails 5.2?

... oh this is what you mean about the micro release of inherit_resources dropping Ruby 2.2

**Comment by ZeroPointEnergy** [comment]
Yes, the current master is 5.2.0 but there is a 5.2.1 which we can only update to if we also update inherit_resources from 1.8.0 to 1.9.0 which then requires at least ruby 2.3

**Comment by bwitt** [comment]
:+1: let's do this update in another major version after 3.0 (try to get 3.0 out as soon as reasonable, don't drop ruby version support in a point release)

**Comment by bwitt** [comment]
... or if ruby 2.2 is not used by anyone, never a system ruby in a major distro, unsupported, etc I'm fine with axing it

**Comment by ZeroPointEnergy** [comment]
The reason while I axed it now is because after the 3.0 release if we do a dependency update it will have to be axed because the inherited_resources gem is depending on ruby >= 2.3.

So I rather remove this now than in a point-release.

**Comment by ZeroPointEnergy** [comment]
Done and merged with #385
