### ISSUE TITLE
Turn on automated security fixes from github

### ISSUE THREAD

**Issue by bwitt** [sodabrew/puppet-dashboard#387]
Now that dependabot is part of github, let's enable automated security fixes from github.

I think  @sodabrew would need to turn on a couple things like 
* security alerts 
* dependency graph

See 
https://help.github.com/en/articles/configuring-automated-security-fixes

**Comment by ZeroPointEnergy** [comment]
I think this would be a good idea. But it looks like even tests and code coverage was disabled again. Should we maybe move this project to a dedicated project account so we can manage it separately?

**Comment by sodabrew** [comment]
I just enabled the new GitHub automated security PRs: 
![image](https://user-images.githubusercontent.com/39406/58804631-2824d780-85c7-11e9-8abe-df72d87539c3.png)

I re-enabled Travis, I'm not sure why that got deactivated.

**Comment by bwitt** [comment]
ok I guess I'll close this since it's enabled even though I haven't seen any security update PRs.

**Comment by ZeroPointEnergy** [comment]
That's because we have all the latest and greatest gems again ;-)
